export interface Athlete {
  id: string
  name: string
  sport: string
  age: number
  location: string
  image?: string
  bio: string
  achievements: string[]
  stats: Record<string, string | number>
  socialMedia: {
    instagram?: string
    twitter?: string
    followers: number
  }
  funding: {
    goal: number
    raised: number
    investors: number
    minInvestment: number
    revenueShare: number
    duration: number
  }
  valuation: number
  riskLevel: "Low" | "Medium" | "High"
  trending: boolean
  featured: boolean
}

export const athletes: Athlete[] = [
  {
    id: "1",
    name: "Marcus Johnson",
    sport: "football",
    age: 22,
    location: "Austin, TX",
    image: "/placeholder.svg?height=400&width=400&text=Marcus+Johnson",
    bio: "Rising quarterback with exceptional arm strength and field vision. Led his college team to three consecutive bowl games.",
    achievements: [
      "Conference Player of the Year 2023",
      "Led team to College Football Playoff",
      "3,500+ passing yards in senior season",
      "Academic All-American",
    ],
    stats: {
      "Passing Yards": "3,542",
      Touchdowns: "28",
      "Completion %": "68.5%",
      QBR: "87.2",
    },
    socialMedia: {
      instagram: "@marcusqb1",
      twitter: "@MarcusJ_QB",
      followers: 45000,
    },
    funding: {
      goal: 500000,
      raised: 387500,
      investors: 234,
      minInvestment: 1000,
      revenueShare: 15,
      duration: 5,
    },
    valuation: 2500000,
    riskLevel: "Medium",
    trending: true,
    featured: true,
  },
  {
    id: "2",
    name: "Sofia Martinez",
    sport: "tennis",
    age: 19,
    location: "Miami, FL",
    image: "/placeholder.svg?height=400&width=400&text=Sofia+Martinez",
    bio: "Promising tennis player with powerful groundstrokes and exceptional court coverage. Junior Grand Slam finalist.",
    achievements: [
      "Junior Wimbledon Finalist 2023",
      "ITF Junior World Ranking #3",
      "Won 12 junior tournaments",
      "Full scholarship to Stanford",
    ],
    stats: {
      "Win Rate": "87%",
      "Aces per Match": "8.5",
      "Break Points Won": "65%",
      Ranking: "#156 WTA",
    },
    socialMedia: {
      instagram: "@sofiaaces",
      twitter: "@SofiaM_Tennis",
      followers: 28000,
    },
    funding: {
      goal: 250000,
      raised: 180000,
      investors: 156,
      minInvestment: 500,
      revenueShare: 12,
      duration: 4,
    },
    valuation: 1800000,
    riskLevel: "Medium",
    trending: true,
    featured: false,
  },
  {
    id: "3",
    name: "Jordan Chen",
    sport: "basketball",
    age: 20,
    location: "Los Angeles, CA",
    image: "/placeholder.svg?height=400&width=400&text=Jordan+Chen",
    bio: "Dynamic point guard with exceptional court vision and three-point shooting ability. Led his team in assists for two consecutive seasons.",
    achievements: [
      "Pac-12 Freshman of the Year",
      "Led conference in assists",
      "Shot 42% from three-point range",
      "Team captain for two years",
    ],
    stats: {
      "Points per Game": "18.5",
      "Assists per Game": "8.2",
      "3-Point %": "42.1%",
      "Steals per Game": "2.1",
    },
    socialMedia: {
      instagram: "@jchen_hoops",
      twitter: "@JordanC_Ball",
      followers: 32000,
    },
    funding: {
      goal: 400000,
      raised: 320000,
      investors: 198,
      minInvestment: 750,
      revenueShare: 18,
      duration: 6,
    },
    valuation: 2200000,
    riskLevel: "Medium",
    trending: true,
    featured: true,
  },
  {
    id: "4",
    name: "Emma Wilson",
    sport: "swimming",
    age: 18,
    location: "Phoenix, AZ",
    image: "/placeholder.svg?height=400&width=400&text=Emma+Wilson",
    bio: "Olympic hopeful in freestyle and butterfly events. Holds multiple junior national records.",
    achievements: [
      "Junior National Champion (100m Butterfly)",
      "Olympic Trials Qualifier",
      "NCAA Division I Scholarship",
      "Set 3 junior national records",
    ],
    stats: {
      "100m Butterfly": "57.23s",
      "200m Freestyle": "1:54.67",
      "National Ranking": "#2 Junior",
      "Personal Bests": "8 events",
    },
    socialMedia: {
      instagram: "@emmaswims",
      twitter: "@EmmaW_Swim",
      followers: 19000,
    },
    funding: {
      goal: 150000,
      raised: 95000,
      investors: 87,
      minInvestment: 250,
      revenueShare: 10,
      duration: 3,
    },
    valuation: 1200000,
    riskLevel: "Low",
    trending: true,
    featured: false,
  },
  {
    id: "5",
    name: "Alex Rodriguez",
    sport: "baseball",
    age: 21,
    location: "Houston, TX",
    image: "/placeholder.svg?height=400&width=400&text=Alex+Rodriguez",
    bio: "Power-hitting first baseman with excellent defensive skills. Projected early-round MLB draft pick.",
    achievements: [
      "Conference Player of the Year",
      "Led team in home runs and RBIs",
      "Golden Glove Award winner",
      "Academic All-Conference",
    ],
    stats: {
      "Batting Average": ".347",
      "Home Runs": "23",
      RBIs: "67",
      "Fielding %": ".995",
    },
    socialMedia: {
      instagram: "@alexrod_baseball",
      twitter: "@AlexR_Baseball",
      followers: 15000,
    },
    funding: {
      goal: 300000,
      raised: 210000,
      investors: 143,
      minInvestment: 500,
      revenueShare: 14,
      duration: 4,
    },
    valuation: 1900000,
    riskLevel: "Medium",
    trending: false,
    featured: true,
  },
  {
    id: "6",
    name: "Maya Patel",
    sport: "golf",
    age: 20,
    location: "Scottsdale, AZ",
    image: "/placeholder.svg?height=400&width=400&text=Maya+Patel",
    bio: "Consistent golfer with exceptional putting skills. Multiple amateur tournament winner.",
    achievements: [
      "Amateur Championship Winner",
      "Lowest scoring average in conference",
      "Curtis Cup Team Member",
      "LPGA Tour card holder",
    ],
    stats: {
      "Scoring Average": "70.2",
      "Driving Distance": "265 yards",
      "Greens in Regulation": "72%",
      "Putting Average": "1.68",
    },
    socialMedia: {
      instagram: "@mayagolf",
      twitter: "@MayaP_Golf",
      followers: 12000,
    },
    funding: {
      goal: 200000,
      raised: 145000,
      investors: 98,
      minInvestment: 400,
      revenueShare: 12,
      duration: 5,
    },
    valuation: 1500000,
    riskLevel: "Low",
    trending: false,
    featured: false,
  },
  {
    id: "7",
    name: "Chris Thompson",
    sport: "track-field",
    age: 22,
    location: "Eugene, OR",
    image: "/placeholder.svg?height=400&width=400&text=Chris+Thompson",
    bio: "Elite sprinter specializing in 100m and 200m events. Olympic trials qualifier.",
    achievements: [
      "NCAA Champion (100m)",
      "Olympic Trials Qualifier",
      "Conference Record Holder",
      "World Championships Team",
    ],
    stats: {
      "100m Personal Best": "9.89s",
      "200m Personal Best": "19.67s",
      "World Ranking": "#12",
      "Season Wins": "8/10",
    },
    socialMedia: {
      instagram: "@chrisruns",
      twitter: "@ChrisT_Track",
      followers: 22000,
    },
    funding: {
      goal: 180000,
      raised: 125000,
      investors: 76,
      minInvestment: 300,
      revenueShare: 11,
      duration: 3,
    },
    valuation: 1400000,
    riskLevel: "Medium",
    trending: true,
    featured: false,
  },
  {
    id: "8",
    name: "Isabella Garcia",
    sport: "soccer",
    age: 19,
    location: "San Diego, CA",
    image: "/placeholder.svg?height=400&width=400&text=Isabella+Garcia",
    bio: "Versatile midfielder with exceptional passing ability and field awareness. Youth national team member.",
    achievements: [
      "Youth National Team Captain",
      "Conference Midfielder of the Year",
      "Led team in assists",
      "Full scholarship recipient",
    ],
    stats: {
      Goals: "12",
      Assists: "18",
      "Pass Accuracy": "89%",
      "Minutes Played": "1,680",
    },
    socialMedia: {
      instagram: "@bellasoccer",
      twitter: "@IsabellaG_Soccer",
      followers: 18000,
    },
    funding: {
      goal: 220000,
      raised: 165000,
      investors: 112,
      minInvestment: 350,
      revenueShare: 13,
      duration: 4,
    },
    valuation: 1600000,
    riskLevel: "Medium",
    trending: false,
    featured: true,
  },
  {
    id: "9",
    name: "Tyler Brooks",
    sport: "football",
    age: 21,
    location: "Atlanta, GA",
    image: "/placeholder.svg?height=400&width=400&text=Tyler+Brooks",
    bio: "Explosive running back with breakaway speed and excellent vision. Led conference in rushing yards.",
    achievements: [
      "Conference Rushing Champion",
      "All-American Honors",
      "2,000+ rushing yards in season",
      "Heisman Trophy Finalist",
    ],
    stats: {
      "Rushing Yards": "2,156",
      Touchdowns: "24",
      "Yards per Carry": "6.8",
      Receptions: "32",
    },
    socialMedia: {
      instagram: "@tylerbrooks_rb",
      twitter: "@TylerB_Football",
      followers: 38000,
    },
    funding: {
      goal: 450000,
      raised: 340000,
      investors: 187,
      minInvestment: 800,
      revenueShare: 16,
      duration: 5,
    },
    valuation: 2300000,
    riskLevel: "Medium",
    trending: true,
    featured: true,
  },
  {
    id: "10",
    name: "Zoe Kim",
    sport: "tennis",
    age: 18,
    location: "Seattle, WA",
    image: "/placeholder.svg?height=400&width=400&text=Zoe+Kim",
    bio: "Rising tennis star with powerful serve and aggressive baseline game. Junior Grand Slam winner.",
    achievements: ["Junior US Open Champion", "ITF Junior World #1", "Won 15 junior titles", "WTA Tour debut at 17"],
    stats: {
      "Win Rate": "91%",
      "Serve Speed": "115 mph",
      "Winners per Match": "28",
      "WTA Ranking": "#89",
    },
    socialMedia: {
      instagram: "@zoetennis",
      twitter: "@ZoeK_Tennis",
      followers: 35000,
    },
    funding: {
      goal: 350000,
      raised: 280000,
      investors: 165,
      minInvestment: 600,
      revenueShare: 14,
      duration: 4,
    },
    valuation: 2100000,
    riskLevel: "Low",
    trending: true,
    featured: false,
  },
  {
    id: "11",
    name: "Marcus Davis",
    sport: "basketball",
    age: 19,
    location: "Chicago, IL",
    image: "/placeholder.svg?height=400&width=400&text=Marcus+Davis",
    bio: "Athletic forward with exceptional rebounding ability and developing three-point shot.",
    achievements: [
      "Conference Freshman of the Year",
      "Led team in rebounds",
      "Double-double in 18 games",
      "McDonald's All-American",
    ],
    stats: {
      "Points per Game": "15.8",
      "Rebounds per Game": "9.4",
      "Field Goal %": "58.2%",
      "Blocks per Game": "1.8",
    },
    socialMedia: {
      instagram: "@mdavis_hoops",
      twitter: "@MarcusD_Ball",
      followers: 25000,
    },
    funding: {
      goal: 320000,
      raised: 240000,
      investors: 134,
      minInvestment: 550,
      revenueShare: 15,
      duration: 5,
    },
    valuation: 1950000,
    riskLevel: "Medium",
    trending: false,
    featured: true,
  },
  {
    id: "12",
    name: "Lily Anderson",
    sport: "swimming",
    age: 17,
    location: "Denver, CO",
    image: "/placeholder.svg?height=400&width=400&text=Lily+Anderson",
    bio: "Versatile swimmer excelling in individual medley and backstroke events. Olympic potential.",
    achievements: [
      "Junior World Championships Medalist",
      "National Age Group Record Holder",
      "Olympic Trials Qualifier",
      "High School All-American",
    ],
    stats: {
      "200m IM": "2:08.45",
      "100m Backstroke": "58.23",
      "National Ranking": "#1 Junior",
      "Personal Records": "6 events",
    },
    socialMedia: {
      instagram: "@lilyswims",
      twitter: "@LilyA_Swim",
      followers: 16000,
    },
    funding: {
      goal: 175000,
      raised: 120000,
      investors: 89,
      minInvestment: 300,
      revenueShare: 11,
      duration: 4,
    },
    valuation: 1350000,
    riskLevel: "Low",
    trending: true,
    featured: false,
  },
  {
    id: "13",
    name: "Jake Martinez",
    sport: "baseball",
    age: 20,
    location: "Tampa, FL",
    image: "/placeholder.svg?height=400&width=400&text=Jake+Martinez",
    bio: "Left-handed pitcher with devastating curveball and pinpoint control. Top draft prospect.",
    achievements: [
      "Conference Pitcher of the Year",
      "Perfect game in championship",
      "Sub-2.00 ERA for two seasons",
      "Academic All-American",
    ],
    stats: {
      ERA: "1.87",
      Strikeouts: "156",
      WHIP: "0.98",
      Wins: "12",
    },
    socialMedia: {
      instagram: "@jakepitches",
      twitter: "@JakeM_Baseball",
      followers: 13000,
    },
    funding: {
      goal: 280000,
      raised: 195000,
      investors: 108,
      minInvestment: 450,
      revenueShare: 13,
      duration: 4,
    },
    valuation: 1750000,
    riskLevel: "Medium",
    trending: false,
    featured: true,
  },
  {
    id: "14",
    name: "Ava Johnson",
    sport: "golf",
    age: 21,
    location: "Augusta, GA",
    image: "/placeholder.svg?height=400&width=400&text=Ava+Johnson",
    bio: "Precision golfer with exceptional short game and mental toughness. Multiple amateur wins.",
    achievements: [
      "Amateur Championship Runner-up",
      "Conference Individual Champion",
      "Curtis Cup Team Selection",
      "LPGA Q-School Graduate",
    ],
    stats: {
      "Scoring Average": "69.8",
      "Driving Accuracy": "78%",
      "Sand Save %": "67%",
      "Top 10 Finishes": "12",
    },
    socialMedia: {
      instagram: "@avagolf",
      twitter: "@AvaJ_Golf",
      followers: 11000,
    },
    funding: {
      goal: 190000,
      raised: 135000,
      investors: 82,
      minInvestment: 350,
      revenueShare: 12,
      duration: 5,
    },
    valuation: 1450000,
    riskLevel: "Low",
    trending: false,
    featured: false,
  },
  {
    id: "15",
    name: "Ryan Cooper",
    sport: "track-field",
    age: 23,
    location: "Boulder, CO",
    image: "/placeholder.svg?height=400&width=400&text=Ryan+Cooper",
    bio: "Distance runner specializing in 5K and 10K events. Marathon potential with sub-2:20 goal.",
    achievements: [
      "NCAA Cross Country Champion",
      "Olympic Marathon Trials Qualifier",
      "Conference Record Holder",
      "Boston Marathon Top 10",
    ],
    stats: {
      "5K Personal Best": "13:45",
      "10K Personal Best": "28:23",
      "Marathon Best": "2:18:45",
      "Weekly Mileage": "120 miles",
    },
    socialMedia: {
      instagram: "@ryanruns",
      twitter: "@RyanC_Distance",
      followers: 20000,
    },
    funding: {
      goal: 160000,
      raised: 110000,
      investors: 71,
      minInvestment: 250,
      revenueShare: 10,
      duration: 3,
    },
    valuation: 1300000,
    riskLevel: "Medium",
    trending: true,
    featured: false,
  },
  {
    id: "16",
    name: "Mia Rodriguez",
    sport: "soccer",
    age: 18,
    location: "Portland, OR",
    image: "/placeholder.svg?height=400&width=400&text=Mia+Rodriguez",
    bio: "Dynamic forward with exceptional speed and finishing ability. Youth national team standout.",
    achievements: [
      "Youth World Cup Golden Boot",
      "Conference Freshman of the Year",
      "Led team in goals and assists",
      "Olympic Development Program",
    ],
    stats: {
      Goals: "22",
      Assists: "14",
      "Shots on Target": "68%",
      Speed: "11.2 seconds (100m)",
    },
    socialMedia: {
      instagram: "@miasoccer",
      twitter: "@MiaR_Soccer",
      followers: 24000,
    },
    funding: {
      goal: 240000,
      raised: 175000,
      investors: 96,
      minInvestment: 400,
      revenueShare: 13,
      duration: 4,
    },
    valuation: 1650000,
    riskLevel: "Medium",
    trending: true,
    featured: true,
  },
  {
    id: "17",
    name: "Ethan Williams",
    sport: "football",
    age: 20,
    location: "Dallas, TX",
    image: "/placeholder.svg?height=400&width=400&text=Ethan+Williams",
    bio: "Versatile wide receiver with reliable hands and route-running precision. Red zone specialist.",
    achievements: [
      "Conference Receiving Champion",
      "All-American Honorable Mention",
      "1,200+ receiving yards",
      "Team Captain",
    ],
    stats: {
      Receptions: "78",
      "Receiving Yards": "1,245",
      Touchdowns: "14",
      "Catch %": "73.6%",
    },
    socialMedia: {
      instagram: "@ethanwilliams_wr",
      twitter: "@EthanW_Football",
      followers: 17000,
    },
    funding: {
      goal: 380000,
      raised: 285000,
      investors: 152,
      minInvestment: 650,
      revenueShare: 15,
      duration: 5,
    },
    valuation: 2050000,
    riskLevel: "Medium",
    trending: false,
    featured: true,
  },
  {
    id: "18",
    name: "Grace Lee",
    sport: "tennis",
    age: 19,
    location: "San Francisco, CA",
    image: "/placeholder.svg?height=400&width=400&text=Grace+Lee",
    bio: "All-court player with exceptional mental toughness and strategic game play. Rising WTA star.",
    achievements: [
      "Junior French Open Semifinalist",
      "ITF Junior Top 10",
      "WTA Tour breakthrough",
      "College Player of the Year",
    ],
    stats: {
      "Win Rate": "84%",
      "Break Points Converted": "58%",
      "First Serve %": "67%",
      "WTA Ranking": "#124",
    },
    socialMedia: {
      instagram: "@gracetennis",
      twitter: "@GraceL_Tennis",
      followers: 21000,
    },
    funding: {
      goal: 290000,
      raised: 220000,
      investors: 127,
      minInvestment: 500,
      revenueShare: 14,
      duration: 4,
    },
    valuation: 1850000,
    riskLevel: "Low",
    trending: false,
    featured: false,
  },
]

export function getTrendingAthletes(): Athlete[] {
  return athletes.filter((athlete) => athlete.trending)
}

export function getFeaturedAthletes(): Athlete[] {
  return athletes.filter((athlete) => athlete.featured)
}

export function getAthletesBySport(sport: string): Athlete[] {
  return athletes.filter((athlete) => athlete.sport.toLowerCase() === sport.toLowerCase())
}

export function getAthleteById(id: string): Athlete | undefined {
  return athletes.find((athlete) => athlete.id === id)
}
